### ISSUE TITLE
27页 Deployment 名称有误

### ISSUE THREAD

**Issue by XanderJi** [kubeguide/K8sDefinitiveGuide-V5-corrigendum#1]
## 书名

- [x] Kubernetes 权威指南（第五版）

## 相关链接

**Comment by yunliushuixian** [comment]
留个联系方式，加个好友吧～
p12-p13的https://虚拟机IP:30001/demo/ 你能打开吗？？我一直是connection refused.

**Comment by leader-us** [comment]
是需要修改名字，谢谢指出

**Comment by kubeguide** [comment]
感谢指正！
