### ISSUE TITLE
p78图中3个kube-apiserver IP地址一样

### ISSUE THREAD

**Issue by TerryHu82** [kubeguide/K8sDefinitiveGuide-V5-corrigendum#12]
## 书名

- [x] Kubernetes 权威指南（第五版）

## 问题所在页码
p78

## 问题描述
图2.5中kube-apiserver 1/2/3的地址写成一样的了,估计是复制的时候没改下面的IP地址,应该是.3/.4/.5

## 相关链接

**Comment by kubeguide** [comment]
感谢指正！
