### ISSUE TITLE
p109 列出在节点server01上运行的所有Pod

### ISSUE THREAD

**Issue by TerryHu82** [kubeguide/K8sDefinitiveGuide-V5-corrigendum#14]
## 书名

- [x] Kubernetes 权威指南（第五版）

## 问题所在页码
p109

## 问题描述
当前命令`kubectl get pods --field-selector=spec.nodeName=server01`只能列出当前namespace下在当前节点所有的pod. 如果想要列出所有ns下的,需要加上`--all-namespaces`

## 相关链接

**Comment by kubeguide** [comment]
感谢指正！
