### ISSUE TITLE
p151 没必要使用k8s.gcr.io/busybox

### ISSUE THREAD

**Issue by TerryHu82** [kubeguide/K8sDefinitiveGuide-V5-corrigendum#18]
## 书名

- [x] Kubernetes 权威指南（第五版）

## 问题所在页码
p151

## 问题描述
image直接使用busybox即可,前面例子都是这样的,没必要换成k8s.gcr.io registry

## 相关链接

**Comment by kubeguide** [comment]
感谢指正！
