### ISSUE TITLE
p153 pod log少打印了一个32

### ISSUE THREAD

**Issue by TerryHu82** [kubeguide/K8sDefinitiveGuide-V5-corrigendum#19]
## 书名

- [x] Kubernetes 权威指南（第五版）

## 问题所在页码
p152
## 问题描述
打印结果应该最后还有一个requests.memory,即32
## 相关链接

**Comment by leader-us** [comment]
修改为
查看 Pod 的日志，可以看到容器启动命令将挂载文件的内容打印出来：
# kubectl logs kubernetes-downwardapi-volume-example-2 
250 
125 
64
32

**Comment by kubeguide** [comment]
感谢指正！
