### ISSUE TITLE
35页 代码和解释中的host不一致

### ISSUE THREAD

**Issue by lzh-lab** [kubeguide/K8sDefinitiveGuide-V5-corrigendum#2]
## 书名

- [x] Kubernetes 权威指南（第五版）

## 问题所在页码
35页

## 问题描述

代码中host是foo.bar.com和bar.foo.com，代码下面的文字解说用的是first.bar.com和second.foo.com

## 相关链接

**Comment by kubeguide** [comment]
应改为：
在以上Ingress的定义中，到虚拟域名foo.bar.com请求的流量会被路由到service1，到bar.foo.com请求的流量会被路由到service2。
感谢指正！
