### ISSUE TITLE
p179 daemonset spec error

### ISSUE THREAD

**Issue by TerryHu82** [kubeguide/K8sDefinitiveGuide-V5-corrigendum#20]
## 书名

- [x] Kubernetes 权威指南（第五版）

## 问题所在页码
p179

## 问题描述
现有yaml文件的selector有误:
~~~
spec:
  template:
    metadata:
      namespace: kube-system
      labels:
        k8s-app: fluentd-cloud-logging
...
~~~
直接运行会出错:
~~~
The DaemonSet "fluentd-cloud-logging" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"k8s-app":"fluentd-cloud-logging"}: `selector` does not match template `labels`
~~~

从[官网](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#writing-a-daemonset-spec)看到,应该是这样:
~~~
spec:
  selector:
    matchLabels:
      name: fluentd-elasticsearch
  template:
    metadata:
      labels:
        name: fluentd-elasticsearch
......
~~~

## 相关链接

**Comment by leader-us** [comment]
apiVersion: apps/v1 
kind: DaemonSet 
metadata: 
 name: fluentd-cloud-logging 
 namespace: kube-system 
 labels: 
    k8s-app: fluentd-cloud-logging
spec: 
 selector:
    matchLabels:
      name: fluentd-elasticsearch
 template: 
    metadata: 
     namespace: kube-system 
     labels: 
       k8s-app: fluentd-cloud-logging 
    spec:

**Comment by leader-us** [comment]
apiVersion: apps/v1 
kind: DaemonSet 
metadata: 
 name: fluentd-cloud-logging 
 namespace: kube-system 
 labels: 
 k8s-app: fluentd-cloud-logging
spec: 
 selector:
    matchLabels:
      name: fluentd-elasticsearch
 template: 
    metadata: 
     namespace: kube-system 
     labels: 
       k8s-app: fluentd-cloud-logging 
    spec:

**Comment by kubeguide** [comment]
感谢指正！
