### ISSUE TITLE
p211 最早来源于heapster组件

### ISSUE THREAD

**Issue by TerryHu82** [kubeguide/K8sDefinitiveGuide-V5-corrigendum#21]
## 书名

- [x] Kubernetes 权威指南（第五版）

## 问题所在页码
p211

## 问题描述
"关于CPU使用率的数据最早来源于组件"
-->
"关于CPU使用率的数据最早来源于Heapster组件"

## 相关链接

**Comment by leader-us** [comment]
多谢纠错
