### ISSUE TITLE
p449 "网站栈"是什么? 是笔误吗

### ISSUE THREAD

**Issue by qiujiafei** [kubeguide/K8sDefinitiveGuide-V5-corrigendum#22]
## 书名

- [x] Kubernetes 权威指南（第五版）

## 问题所在页码
 p449 第三段
## 问题描述
 原文: 所有网站栈变量都放入网络名称空间
## 相关链接

**Comment by leader-us** [comment]
所有**网络协议栈变量**都被放入了网络命名空间的数据结构中。

应该是这样的，谢谢
