### ISSUE TITLE
p235 mongoDB statefulset

### ISSUE THREAD

**Issue by TerryHu82** [kubeguide/K8sDefinitiveGuide-V5-corrigendum#23]
## 书名

- [x] Kubernetes 权威指南（第五版）

## 问题所在页码
p235, p236多处
## 问题描述
错误1: statefulset配置中缺少selector配置
~~~
spec:
  selector:
    matchLabels:
      role: mongo
  serviceName: "mongo"
.....
~~~

错误2: 使用最新的mongoDB image已经跑不通了, 会出现

~~~
Error parsing command line: unrecognised option '--smallfiles' 
Error parsing command line: unrecognised option '--noprealloc'
~~~

而且即使注释掉这两个启动参数,也会出现connection refused,集群无法连接的情况. 从书中可以看出,当时还是3.4.4的旧版本, 这都是4年前的版本了,现在拉Mongo image已经升级到了5.0.
希望在每次书出新版的时候,都用最新的image重新测一下,很有可能image已经更新,产品出现变化,旧的参数不再适用,或者需要新的参数的情况. 如果不愿意用新image测试,也至少指定一下可以跑通的tag,比如这个问题,使用`3.4.4`即可以解决.
## 相关链接

**Comment by leader-us** [comment]
感谢指出问题。
