### ISSUE TITLE
p260 service支持的网络协议: HTTP和PROXY

### ISSUE THREAD

**Issue by TerryHu82** [kubeguide/K8sDefinitiveGuide-V5-corrigendum#24]
## 书名

- [x] Kubernetes 权威指南（第五版）

## 问题所在页码
p260

## 问题描述
HTTP和PROXY的描述都是"取决于云服务商是否支持HTTP和实现机制", PROXY的是否应该改为"是否支持Proxy.."

## 相关链接

**Comment by leader-us** [comment]
感谢指正。
