### ISSUE TITLE
P366 K8s HTTPS证书认证描述是否有误

### ISSUE THREAD

**Issue by ounijang** [kubeguide/K8sDefinitiveGuide-V5-corrigendum#27]
## 书名

- [x] Kubernetes 权威指南（第五版）

## 问题所在页码
P366、P367

## 问题描述
P366, P367  CA认证工作流程：第(3),(4)点

原文：(3)客户端向服务端发起请求，服务端下发服务端证书给客户端。客户端在接收到证书后，通过**私钥**解密证书，.....
问题：“通过**私钥**解密证书”这段话描述有误，HTTPS双向认证原理中客户端应该是使用CA的公钥来解密服务端的证书并验证。
1、这里使用私钥解密服务端证书，使用的是谁的私钥，如果是客户端私钥，建立连接之前那服务端又是如何获取到客户端公钥的，并通过客户端公钥加密自己的证书，然后再发给客户端；或者是服务端公钥加密，那客户端又是如何获取到服务端私钥的。**明显不成立，服务端和客户端不可能持有对方的私钥。**

原文：(4)客户端发送客户端证书给服务端，服务端在接收到证书后通过**私钥**解密证书，.......
问题：“服务端在接收到证书后通过**私钥**解密证书”这段话描述有误，HTTPS双向认证原理中服务端应该是使用CA的公钥来解密客户端的证书并验证。
## 相关链接

**Comment by leader-us** [comment]
感谢支出问题，确实是写错了。
