### ISSUE TITLE
p153 笔误

### ISSUE THREAD

**Issue by YTGhost** [kubeguide/K8sDefinitiveGuide-V5-corrigendum#29]
## 书名

- [x] Kubernetes 权威指南（第五版）

## 问题所在页码

第153页

## 问题描述

底部倒数第二行中，metadata.annotation写错为metadata.namannotations

## 相关链接

![image](https://user-images.githubusercontent.com/40822107/141975252-3eb11f0c-a63b-4ac9-b6cb-735b562347b0.png)

**Comment by leader-us** [comment]
感谢反馈，确实笔误
