### ISSUE TITLE
P191 笔误

### ISSUE THREAD

**Issue by YTGhost** [kubeguide/K8sDefinitiveGuide-V5-corrigendum#30]
## 书名

- [x] Kubernetes 权威指南（第五版）

## 问题所在页码

P191

## 问题描述

Zone B的 skew=1-0=0，应该改成1-0=1

## 相关链接
![image](https://user-images.githubusercontent.com/40822107/142882822-1ea9e321-a49e-4d00-b274-63c7a52ffd97.png)

**Comment by leader-us** [comment]
感谢反馈，确实笔误
