### ISSUE TITLE
p342 工作流程图 笔误

### ISSUE THREAD

**Issue by ArcadioStudio** [kubeguide/K8sDefinitiveGuide-V5-corrigendum#31]
## 书名

- [x] Kubernetes 权威指南（第五版）

## 问题所在页码

p342

## 问题描述

流程图中 “用Master节点的系统**事件**作为探测时间” 应改为 “用Master节点的系统**时间**作为探测时间”
左右两个模块都出现了错误

## 相关链接

**Comment by leader-us** [comment]
@

> 

多谢反馈，确实笔误
