### ISSUE TITLE
配置文件不完整

### ISSUE THREAD

**Issue by PysomeZh** [kubeguide/K8sDefinitiveGuide-V5-corrigendum#32]
## 书名

- [x] Kubernetes 权威指南（第五版）

## 问题描述
 对ConfigMap的定义如下：（第六行）data：之后没有数据

运行后出现错误“error: error parsing 4.6.1 ingress.yaml: error converting YAML to JSON: yaml: line 22: could not find expected ':'”

**Comment by kubeguide** [comment]
yaml文件已更新，请重新下载，谢谢！
