### ISSUE TITLE
配置文件名不正确

### ISSUE THREAD

**Issue by PysomeZh** [kubeguide/K8sDefinitiveGuide-V5-corrigendum#33]
## 书名

- [x] Kubernetes 权威指南（第五版）

## 问题描述
   * kubectl create -f nginx-ingress-daemonset.yaml  文件名错误，因：https://github.com/kubeguide/k8sdefinitiveguide-v5-sourcecode 源码中没有nginx-ingress-daemonset.yaml ， 根据上下文判断，有个ingress.yaml的文件，应更正为此文件名。
 

## 相关链接

**Comment by kubeguide** [comment]
由于前文在第299页给出的配置文件名为nginx-ingress-controller.yaml，所以此处应改为：
`# kubectl create -f nginx-ingress-controller.yaml`
源代码中的文件名也重命名为“4.6.1 nginx-ingress-controller.yaml”了

感谢指正！
