### ISSUE TITLE
Web示例测试失败

### ISSUE THREAD

**Issue by yuluo-yx** [kubeguide/K8sDefinitiveGuide-V5-corrigendum#48]
## 书名
- [x] Kubernetes 权威指南（第五版）

## 问题所在页码
12

## 问题描述
pod和svc如下：
![image](https://user-images.githubusercontent.com/77964041/227766627-8a61cf05-f1a3-4cd0-a986-6433c4322f41.png)

在我使用minikube作为k8s环境搭建了测试web用例之后，无法访问demo示例.
但是可以正常访问 tomcat 首页，即8080端口。
```shell
root@kubernetes:/home/yuluo# kubectl get node -o wide
NAME       STATUS   ROLES                  AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
minikube   Ready    control-plane,master   43m   v1.23.1   192.168.49.2   <none>        Ubuntu 20.04.2 LTS   5.15.0-67-generic   docker://20.10.12

之后分别使用命令访问
curl 192.168.49.2:30001
curl 192.168.49.2:30001/demo
```

访问结果如下：
![image](https://user-images.githubusercontent.com/77964041/227766569-cce64f3a-b9ac-4ff8-bd4b-19f64f11dd57.png)

**Comment by kubeguide** [comment]
通常是后端mysql没有正常运行，或者myweb连接mysql的配置不正确导致的
