### ISSUE TITLE
208页 DaemonSet的更新策略，默认应该是RollingUpdate

### ISSUE THREAD

**Issue by lzh-lab** [kubeguide/K8sDefinitiveGuide-V5-corrigendum#5]
## 书名

- [x] Kubernetes 权威指南（第五版）

## 问题所在页码
208
## 问题描述
DaemonSet的更新策略，默认应该是RollingUpdate

目前在Deployment DaemonSet StatefulSet的默认updateStrategy都是RollingUpdate
## 相关链接

**Comment by kubeguide** [comment]
感谢指正！
