### ISSUE TITLE
Kubernetes Clusterrole

### ISSUE THREAD

**Issue by ajie1027** [kubeguide/K8sDefinitiveGuide-V5-corrigendum#52]
## 书名

- [x] Kubernetes 权威指南（第五版）

## 问题所在页码
384
## 问题描述
384页最后一段话，“用户就无法修改与之绑定的Role或ClusterRole了。只有删除了RoleBinding或ClusterRoleBinding”;
但是我在实际的1.28.0版本的k8s集群中去验证的时候，是可以直接修改ClusterRole的，并且修改后与之绑定的sa权限也是生效了的
可创建相关资源进行验证
## 相关链接

**Comment by ajie1027** [comment]
是我理解错了 它的意思是不能直接修改clusterbinding和rolebinding 我测试了一下 书上写的是对的

**Comment by kubeguide** [comment]
感谢验证！
