### ISSUE TITLE
p13访问不了30001端口还有另外一种情况

### ISSUE THREAD

**Issue by dairongpeng** [kubeguide/K8sDefinitiveGuide-V5-corrigendum#7]
## 书名

- [x] Kubernetes 权威指南（第五版）

## 问题所在页码
 
p13

## 问题描述

这是第三种无法打开网页的情况 ： 如果是集群部署，那么如果集群master仅仅作为资源调度中心的话。部署的资源会被分配到node节点，所以mster-ip:30001是不通的。docker ps | grep myweb 看看资源在哪个node上，再使用node-ip:30001，访问

**Comment by leader-us** [comment]
本书的配套环境里，以及默认大部分学习环境都是Master节点同时作为Node节点，所以本书的说法没问题，您这里的提醒是不错的，不过有个细节，就是30001端口跟具体的Node无关。
