### ISSUE TITLE
图文不符

### ISSUE THREAD

**Issue by leigh8755** [kubeguide/K8sDefinitiveGuide-V5-corrigendum#8]
## 书名

- [x] Kubernetes 权威指南（第五版）

## 问题所在页码
35
## 问题描述
灰框范例里的host名字和正文第一行第二行讲解的域名不一致
## 相关链接

**Comment by leader-us** [comment]
原文
在以上 Ingress 的定义中，到虚拟域名 first.bar.com 请求的流量会被路由到 service1，
到 second.foo.com 请求的流量会被路由到 service2。
新文
在以上 Ingress 的定义中，到虚拟域名 foo.bar.com 请求的流量会被路由到 service1，
到 bar.foo.com 请求的流量会被路由到 service2。

确定是文中名字错误，多谢指出。

**Comment by kubeguide** [comment]
感谢指正！
