### ISSUE TITLE
curl错误

### ISSUE THREAD

**Issue by gaochuang** [kubeguide/K8sDefinitiveGuide-V5-corrigendum#9]
书名
Kubernetes 权威指南（第五版）
问题所在页码
260
问题描述
curl http://${WEBAPP_SERVICE_HOST}**:${WEBAPP_SERVICE_HOST}**应该为curl http://${WEBAPP_SERVICE_HOST}**:${WEBAPP_SERVICE_PORT}**

**Comment by leader-us** [comment]
确实提议修改正确，书中笔误，谢谢。

**Comment by kubeguide** [comment]
感谢指正！
